### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by macshaggy** [felixjung/repl-term#2]
[Enter steps to reproduce below:]

1. CMD-OPT-L to launch the REPL.
2. Received the error.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [repl-term](https://github.com/felixjung/repl-term) package, v0.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/macshaggy/.atom/packages/repl-term/lib/language-handler.coffee:6

TypeError: undefined is not a function
  at Object.module.exports.currentLanguage (/Users/macshaggy/.atom/packages/repl-term/lib/language-handler.coffee:6:32)
  at Object.module.exports.launchRepl (/Users/macshaggy/.atom/packages/repl-term/lib/terminal-handler.coffee:24:34)
  at atom-workspace.subscriptions.add.atom.commands.add.repl-term:launch-repl (/Users/macshaggy/.atom/packages/repl-term/lib/repl-term.coffee:11:51)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:15.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:close (div.settings-view.pane-item)
     -0:05.4.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:04.9.0 repl-term:launch-repl (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "github-issues",
      "autocomplete-clang",
      "language-rust",
      "racer",
      "linter-rust"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/macshaggy/workspace"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
git-tab-status, v1.9.2
linter, v1.1.0
linter-clang, v2.26.0
linter-jshint, v0.1.7
linter-tidy, v1.0.1
minimap, v4.10.2
omnisharp-atom, v0.17.3
repl-term, v0.1.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by felixjung** [comment]
This should be fixed with version 0.1.2
