### ISSUE TITLE
syntax error: Expected end of line but found “"”. (-2741)↵"

### ISSUE THREAD

**Issue by sasquatch666** [felixjung/repl-term#5]
Cannot launch from Python, I get this error in console.

Also cannot launch from unsupported file extensions, was hoping I could at least open a terminal.

Using OS X Yosemite.

**Comment by felixjung** [comment]
Hi, thanks for reporting this. Can you give me a slightly more precise description of how to reproduce this problem?

**Comment by sasquatch666** [comment]
I get this immediately after trying to launch with Cmd-alt-L from any file.  I am running 10.10.4, Atom 1.0.5.  Don't have a lot of packages installed, just the following (aside from the stock):
language-latex, latex, latexer, linter, linter-chktex, linter-flake8, pdf-view, repl-term
Let me know any other details you need, or things to try for debugging!

Error: 917:918: syntax error: Expected end of line but found “"”. (-2741)
 {stack: (...), message: "917:918: syntax error: Expected end of line but found “"”. (-2741)↵"}
message: "917:918: syntax error: Expected end of line but found “"”. (-2741)↵"

stack: "Error: 917:918: syntax error: Expected end of line but found “"”. (-2741)↵↵  at ChildProcess.<anonymous> (/Users/mrodgers/.atom/packages/repl-term/node_modules/node-osascript/lib/index.js:34:15)↵  at emitTwo (events.js:87:13)↵  at ChildProcess.emit (events.js:169:7)↵  at maybeClose (child_process.js:997:16)↵  at Socket.<anonymous> (child_process.js:1166:11)↵  at emitOne (events.js:77:13)↵  at Socket.emit (events.js:166:7)↵  at Pipe.close (net.js:464:12)↵"

get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: d
(anonymous function)  /Users/mrodgers/.atom/packages/repl-term/lib/terminal-handler.coffee:61 
(anonymous function)  /Users/mrodgers/.atom/packages/repl-term/node_modules/node-osascript/lib/index.js:44 
emitTwo                        events.js:87 
emit                               events.js:169 
maybeClose                  child_process.js:997 
(anonymous function)   child_process.js:1166 
emitOne                        events.js:77 
emit                               events.js:166 
(anonymous function)   net.js:464

**Comment by felixjung** [comment]
Sorry, I wasn't able to reproduce this. Are you running the latest version?

**Comment by sasquatch666** [comment]
Yes, I was using 0.2.2. I just activated, checked for updates, and tested again (Atom 1.0.11 now).

**Comment by datafig** [comment]
I am experiencing same issue. Latest version of Atom 1.0.18 and the interpreter is Julia.
